# Generated by Django 5.1.3 on 2024-12-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_datetime',
        ),
    ]
